openapi: 3.0.4
info:
  version: 1.0.0
  title: Account Service API
servers:
  - url: http://localhost:8086
paths:
  /api/accounts:
    post:
      summary: Create a new bank account
      operationId: createAccount
      tags:
        - account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Account"
      responses:
        '201':
          description: Account created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        '400':
          description: Invalid data
    get:
      summary: Get all accounts
      operationId: getAllAccounts
      tags:
        - account
      responses:
        '200':
          description: List of accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Account"
  /api/accounts/{id}:
    get:
      summary: Get account by ID
      operationId: getAccountById
      tags:
        - account
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Account details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        '404':
          description: Account not found
    delete:
      summary: Delete an account
      operationId: deleteAccount
      tags:
        - account
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Account deleted successfully
        '404':
          description: Account not found
    put:
      summary: Update an existing account
      operationId: updateAccount
      tags:
        - account
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Account"
      responses:
        '200':
          description: Account updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        '404':
          description: Account not found
        '400':
          description: Invalid data
  /api/accounts/{id}/deposit:
    put:
      summary: Deposit amount into account
      operationId: deposit
      tags:
        - account
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DepositRequest"
      responses:
        '200':
          description: Deposit successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        '400':
          description: Invalid data
  /api/accounts/{id}/withdraw:
    put:
      summary: Withdraw amount from account
      operationId: withdraw
      tags:
        - account
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WithdrawRequest"
      responses:
        '200':
          description: Withdrawal successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        '400':
          description: Invalid data
components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: string
        customerId:
          type: string
        customerType:
          type: string
          enum:
            - PERSONAL
            - EMPRESARIAL
        accountType:
          type: string
          enum:
            - AHORRO
            - CORRIENTE
            - PLAZO_FIJO
        balance:
          type: number
          format: double
        monthlyLimit:
          type: integer
          description: Only applicable for CORRIENTE accounts
        lastDepositDate:
          type: string
          format: date
          description: Only applicable for PLAZO_FIJO accounts
        holders:
          type: array
          items:
            type: string
    DepositRequest:
      type: object
      properties:
        monto:
          type: number
          format: double
    WithdrawRequest:
      type: object
      properties:
        monto:
          type: number
          format: double

